### ISSUE TITLE
Problems about some details

### ISSUE THREAD

**Issue by BraveDrXuTF** [zongyi-li/Geo-FNO#1]
Excellent work! And I have some questions about some details.

1. "The target output is stress." in section Hyper-elastic material in the paper.  What does the stress mean here? Is it a Mises-stress or some type stress tensor? I guess it a Mises-stress, because in the code I found `out_channel` is set to 1.
2. Could 2-dim geoFNO handle the problem of multichannel output? For example, given geometry and boundary, could the 2-dim FNO output a stress tensor?

**Comment by zongyi-li** [comment]
Thanks!

1. yes, the output is the Mises-stress.
2. yes, it's possible to output the stress tensor. Usually, we just use a larger out_channel.

**Comment by BraveDrXuTF** [comment]
Yeah, I mean, in my experiment using a larger out_channel doesn't go well often, and in fact in many papers **they just use muti models**, which raises a question for me.
You know, in solid mechanics, we have a vector of field output (every element of the vector is a function in field). And I wonder if the term"Neural Operator" in which the word "operator" means _a mapping from **_a function space_** to another in math_,  implies that a single operator model cannot predict a vector field very well. And I believe we may create a stronger model to predict muti channel output.


> Thanks!
> 
> 1. yes, the output is the Mises-stress.
> 2. yes, it's possible to output the stress tensor. Usually, we just use a larger out_channel.

**Comment by zongyi-li** [comment]
I see. If a larger out_channel doesn't go well, you can try with more sophisticated methods like the Clifford neural operators https://arxiv.org/pdf/2209.04934.pdf

**Comment by BraveDrXuTF** [comment]
Wow, that's amazing!

> I see. If a larger out_channel doesn't go well, you can try with more sophisticated methods like the Clifford neural operators https://arxiv.org/pdf/2209.04934.pdf
