### ISSUE TITLE
Fix the bug in plasticity_3d.py

### ISSUE THREAD

**Issue by wuhaixu2016** [zongyi-li/Geo-FNO#3]
It seems like we need to add the `optimizer.step()` in line 228 of `plasticity_3d.py`.
Without this line of code, the model cannot be optimized during training.

**Comment by zongyi-li** [comment]
Thanks for the catch! It was probably mistakenly removed when we cleaned and uploaded the code.

**Comment by wuhaixu2016** [comment]
Thanks for your prompt reply.
